W4D5/harmonia_capybara/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums

  resources :albums do
    resources :tracks
  end

  resources :tracks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

W4D5/harmonia_capybara/app/models/album.rb
class Album < ApplicationRecord
  validates :title, presence: true

  belongs_to :band,
  primary_key: :id,
  foreign_key: :band_id,
  class_name: 'Band'
end

W4D5/harmonia_capybara/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :albums,
  primary_key: :id,
  foreign_key: :band_id,
  class_name: 'Album'
end

W4D5/harmonia_capybara/app/models/track.rb
class Track < ApplicationRecord

    belongs_to :album
    primary_key: :id,
    foreign_key: :album_id
    class_name: 'Album'

    has_one :band,
    through: :album,
    source: :band



end

W4D5/harmonia_capybara/app/models/user.rb
class User < ApplicationRecord

  after_initialize :ensure_session_token
  attr_reader :password
  validates :password_digest, presence: true
  validates :username, :email, presence: true
  validates :username, :email, uniqueness: true
  validates :password, length: { minimum: 7, allow_nil: true }

  def self.find_by_credentials(uname, pword)
    # user = User.find_by(username: username)
    # user && user.is_password?(password) ? user : nil
    #This syntax MUST become muscle memory
    user = User.find_by(username: uname)
    user && user.is_password?(pword) ? user : nil
  end

  def ensure_session_token
      self.session_token ||= SecureRandom.urlsafe_base64
  end

  def self.generate_session_token
    self.session_token = SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    #assign, save, return.
    #assign, save , return
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def password=(pword)
    @password = pword
    self.password_digest = BCrypt::Password.create(pword)
  end

  def is_password?(pword)
    BCrypt::Password.new(self.password_digest).is_password?(pword)
  end



end

W4D5/harmonia_capybara/app/controllers/albums_controller.rb
class AlbumsController <  ApplicationController

  def new
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new
    if @album.save
      redirect_to band_album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

W4D5/harmonia_capybara/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
helper_method :current_user, :logged_in?, :login!

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

 def logged_in?(user)
  !!current_user
 end

 def login!(user)
   @current_user = user
   session[:session_token] = user.reset_session_token!
 end

 def logout!
     current_user.reset_session_token!
     session[:session_token] = nil
     @current_user = nil
   end

end

W4D5/harmonia_capybara/app/controllers/bands_controller.rb
class BandsController < ApplicationController

 def index
   @bands = Band.all
   render :index
 end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
private
def band_params
  params.require(:band).permit(:name)
end


end

W4D5/harmonia_capybara/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

QUIPS = [
  "thy knave!",
  "ye blackguard!",
  "ya wascally wabbit!",
  "silly!",
  "dude!",
  "you dun goofed!",
  "have an iced herbal tea and try again.",
  "do not pass GO, do not collect $200",
  "YOU SHALL NOT PASS!!",
  "request denied.",
  "you are the weakest link..goodbye!",
  "easter egg message!",
  ", i spent an entire day working on this and this is the thanks I get?"
]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = ["Invalid credentials, #{QUIPS.sample}"]
      render :new
    end


  end

  def destroy
    logout!
    redirect_to new_session_url
  end

end

W4D5/harmonia_capybara/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def index
    @users = User.all
    render :index
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def edit
  end

  def update
  end

  private
  def user_params
     params.require(:user).permit(:username, :password, :email)
  end

end

W4D5/harmonia_capybara/app/helpers/application_helper.rb
module ApplicationHelper
  # def auth_token
  #   <input type="hidden" value="<%=form_authenticity_token %>" name= "authenticity_token">
  # end
end

W4D5/harmonia_capybara/app/views/albums/new.html.erb
<form action="<%=new_band_album_url%>" method="post">
  <input type="hidden" name="authenticity_token" value='<%= form_authenticity_token %>'/>
  <label for="album_title"> Album Title: </label>
  <input type="text" name="album[title]">
  <br>
  <label for="album_title"> Album Year: </label>
  <input type="text" name="album[year]">
  <br>
  <label for="band">Select Band</label>
  <select name="album[band_id]">
      <% Band.all.each do |band| %>
      <option><%=band.name %></option>
      <% end %>
  </select>
  <br>
  <label for="radio">Album Type</label>
  <input type="radio" name="album[studio]">
  <br>
  <input type="submit" name="Submit">

</form>

<!-- For the views:

Have a drop-down to select which Band recorded the Album.
Use selected to default-select the appropriate Band in the drop-down.
Use radio buttons to select whether the album is a live or studio album.
Don't use a column named type, since Rails uses this for a special purpose and everything
will break. Use checked to default select the appropriate value.
Make sure to provide links back to the album's band and make edit/delete buttons
visible from the album's show page
Update the Band show page to list/link to all of the band's albums and create a new one -->

W4D5/harmonia_capybara/app/views/albums/show.html.erb
<% album = Album.find(params[:id]) %>
<h1><%=album.name%></h1>

W4D5/harmonia_capybara/app/views/bands/index.html.erb
<h2> List of Bands </h2>

<ul>
<% @bands.each do |band| %>
<li> <a href = "<%= band_url(band[:id]) %>" style="font-weight: bold;"> <%= band.name %>  </li>
  <% end %>
</ul>

W4D5/harmonia_capybara/app/views/bands/new.html.erb
<h2>Enter a New Band into our Rockin' Database </h2>
<form action='/bands' method="post">
  <input type="hidden" name="authenticity_token" value='<%= form_authenticity_token %>'/>
  <label for="band_name">Band Name</label>
  <input type="text" name="band[name]">
  <input type="submit" value="Create!">
</form>

W4D5/harmonia_capybara/app/views/bands/show.html.erb
<head>
<link rel="stylesheet" type="text/css" href="app/assets/stylesheets/band_style.css">
</head>
<% band = Band.find(params[:id]) %>
<h1 id="band_name"><%=band.name%></h1>

<h3> Albums By <%=band.name %><h3
  <!-- Table of albums with clickable links goes here -->
  <a href ="<%=new_band_album_url(band.id)%>"> <button> Add a New Album</button> </a>
  <a href ="<%=bands_url%>"> <button> Return to Bands</button> </a>

W4D5/harmonia_capybara/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Harmonia</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<header>
  <h1 id="header_title">Harmonia - Your High-Tech Music Library</h1>
  <% if current_user.nil? %>
    <a href ="<%= new_user_url %>"> <button> New User </button> </a>
    <a href ="<%= new_session_url %>"><button> Log In </button> </a>
  <% else %>
  <h3>Logged in as: <%= current_user.username %></h3>
  <form class="" action="<%= session_url %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="delete">
        <input type="submit" name="" value="Log Out">
      </form>
  <% end %>

</header>


  <body>
<% if flash[:errors]%>
<ul>
<%  flash[:errors].each do |err| %>
<li><%= err %></li>
<% end %>
</ul>
<% end %>

    <%= yield %>
  </body>
</html>

W4D5/harmonia_capybara/app/views/users/index.html.erb
<h1> List of Our Harmonious Contributors</h1>
<h2> Click on a link below to view a profile! </h2>

<ul>
<% @users.each do |user| %>
  <li> <a href = "<%= user_url(user[:id]) %>" style="font-weight: bold;"> <%= user.username %>  </li>
    <br>
  <% end %>
</ul>

W4D5/harmonia_capybara/app/views/users/new.html.erb
<h1>Greetings, music fan!</h1>
<h2>Welcome to Harmonia, an interactive online musical database.</h2>
<h2>Please sign up to help us build our high-tech encyclopedia!</h2>
  <br>

<form action="/users/" method="post">
  <input type="hidden" name="authenticity_token" value='<%= form_authenticity_token %>'/>
  <label for="username"> Username: </label>
  <input id="username" type="text" name="user[username]">
  <br>
  <label for="email"> Email: </label>
  <input id="email" type="email" name="user[email]">
    <br>
  <label for="password"> Password:</label>
  <input id="password" type="password" name="user[password]">
  <br>
  <input id="submit" type="submit" value="Sign Up">
</form>

W4D5/harmonia_capybara/app/views/users/show.html.erb
<h1> <%=@user.username%>'s Most Musical Home Page' </h1>
<% if current_user == @user %>
<h2> Hello, <%= @user.username%>! Welcome back!</h2>
<% end %>
<br> <br>